export const queryKeys = {
  appearanceSettings: ["settings", "appearance"] as const,
  systemMetrics: ["system", "metrics"] as const,
  systemPreferences: ["system", "preferences"] as const,
  systemUpdates: ["system", "updates"] as const,
  systemSecurity: ["system", "security"] as const,
  systemBackups: ["system", "backups"] as const,
  networkStatus: ["network", "status"] as const,
  networkNetworks: ["network", "networks"] as const,
  installedApps: ["apps", "installed"] as const,
  currentUser: ["auth", "current-user"] as const,
  storeCatalog: ["store", "catalog"] as const,
  storeSources: ["store", "sources"] as const,
  storeApp: (appId: string) => ["store", "app", appId] as const,
  appCompose: (appId: string, source: "catalog" | "installed" = "catalog") =>
    ["store", "app-compose", appId, source] as const,
  storeOperation: (operationId: string) =>
    ["store", "operation", operationId] as const,
  filesRoot: ["files", "root"] as const,
  filesStarred: ["files", "starred"] as const,
  filesList: (filePath: string, includeHidden = false) =>
    ["files", "list", filePath, includeHidden] as const,
  fileContent: (filePath: string) => ["files", "content", filePath] as const,
  networkShares: ["files", "network", "shares"] as const,
  localFolderShares: ["files", "shared", "folders"] as const,
  trashEntries: (filePath: string) => ["files", "trash", "entries", filePath] as const,
  filesSearch: (query: string, basePath: string, includeHidden: boolean) =>
    ["files", "search", query, basePath, includeHidden] as const,
  currentWeather: (latitude: number | null, longitude: number | null) =>
    ["weather", "current", latitude, longitude] as const,
  dockerInfo: ["docker", "info"] as const,
  powerSchedule: ["system", "power", "schedule"] as const,
  powerCapabilities: ["system", "power", "capabilities"] as const,
  logs: (source: "homeio" | "system" | "docker") =>
    ["logs", source] as const,
  notifications: ["notifications"] as const,
  scheduledTasks: ["scheduled-tasks"] as const,
  taskExecutions: (taskId: string) => ["scheduled-tasks", taskId, "executions"] as const,
  googleOAuthConfig: ["google-oauth", "config"] as const,
  tailscaleConfig: ["tailscale", "config"] as const,
  tailscaleStatus: ["tailscale", "status"] as const,
  cloudflareTunnelConfig: ["cloudflare-tunnel", "config"] as const,
  cloudflareTunnelExposures: ["cloudflare-tunnel", "exposures"] as const,
  cloudflareTunnelStatus: ["cloudflare-tunnel", "status"] as const,
  googleDriveConnections: ["google-drive", "connections"] as const,
  googleDriveBrowse: (connectionId: string, folderId: string) =>
    ["google-drive", "browse", connectionId, folderId] as const,
  usbDrives: ["files", "usb"] as const,
  disks: ["system", "disks"] as const,
  serverInfo: ["system", "info"] as const,
  entitlements: ["licensing", "entitlements"] as const,
};
